[package]
name = "tick"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "3.0.0"
jfs = "0.9.0"
nanoid = "0.4.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
